# Generated by Django 3.2 on 2021-05-05 21:06

from django.db import migrations, models
import django.db.models.deletion
import omnistack9.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.CharField(default=omnistack9.models.get_uuid_8_length, editable=False, max_length=8, primary_key=True, serialize=False)),
                ('thumbail', models.ImageField(blank=True, upload_to='uploads/%Y/%m/%d/')),
                ('company', models.CharField(max_length=50)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('techs', models.ManyToManyField(related_name='spot_techs', to='omnistack9.Tech')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='omnistack9.user')),
            ],
        ),
    ]
