# Generated by Django 3.2 on 2021-05-06 03:45

from django.db import migrations, models
import omnistack9.models


class Migration(migrations.Migration):

    dependencies = [
        ('omnistack9', '0002_auto_20210506_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_new',
            field=models.CharField(default=omnistack9.models.get_uuid_8_length, max_length=8),
        ),
    ]
