# Generated by Django 3.2 on 2021-05-06 05:20

from django.db import migrations, models
import omnistack9.models


class Migration(migrations.Migration):

    dependencies = [
        ('omnistack9', '0004_auto_20210506_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='price',
            field=models.CharField(default='50.00', max_length=8),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default=omnistack9.models.get_uuid_8_length, editable=False, max_length=8, primary_key=True, serialize=False),
        ),
    ]
