# Generated by Django 3.2 on 2021-05-07 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omnistack9', '0006_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
