# Generated by Django 3.2 on 2021-05-07 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omnistack9', '0007_alter_spot_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='price_new',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
