# Generated by Django 3.2 on 2021-05-07 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omnistack9', '0008_spot_price_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spot',
            name='price',
        ),
    ]
