# Generated by Django 3.2 on 2021-05-07 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omnistack9', '0009_remove_spot_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spot',
            old_name='price_new',
            new_name='price',
        ),
    ]
