# Generated by Django 3.2 on 2021-05-08 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omnistack9', '0010_rename_price_new_spot_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spot',
            old_name='thumbail',
            new_name='thumbnail',
        ),
    ]
