# Generated by Django 3.2 on 2021-05-11 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omnistack9', '0011_rename_thumbail_spot_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('R', 'Requested'), ('A', 'Answered'), ('V', 'Viewed')], default='R', max_length=1),
        ),
    ]
